### ISSUE TITLE
Calculate for yolo3 from gluoncv ?

### ISSUE THREAD

**Issue by djaym7** [Ldpe2G/DeepLearningForFun#6]

**Comment by Ldpe2G** [comment]
@djaym7  you can export the yolov3 to json file, then you can use `calculateFlops.py` script to calculate the flops.

**Comment by djaym7** [comment]
What would be the label? There are 3 output branches.

**Comment by Ldpe2G** [comment]
The script support multi-labels, you can ues the `-ls` parameter.

**Comment by djaym7** [comment]
![image](https://user-images.githubusercontent.com/12378820/72765069-79f29000-3b9f-11ea-9d96-67964bf0e5e1.png)

Idk what to put in for label shapes. There is no argument for concat op, the yolov38_yolooutputv30 , 31 and 32 has offset and anchors, dont know which ones to put, offsets or anchors. Also, write three layers at once in a list or tuple in label names -- how?

@zhreshold  any help on label_names  for yolo3. I am trying to load symbol and bind it, warning is shown in the image?

**Comment by Ldpe2G** [comment]
@djaym7 I can succefully running the  `calculateFlops.py` script with glouncv `yolo3_darknet53_voc` model. you can try the following command :
` python calflops.py -s yolo3_darknet53_voc-symbol.json -ds data,1,3,224,224`
You don't need to provide the label infomations because the symbol is only for infer and does not contain any label nodes.

you should get the following output:
```
('flops: ', '9485.197687', ' MFLOPS')
('model size: ', '235.459789276', ' MB') 
```
And remember to remove `_fwd` suffix  of all the layers' name if the model you used is export from gloun.

**Comment by djaym7** [comment]
Thank you

**Comment by zhreshold** [comment]
Just to mention that yolo3 usually takes input such as (1, 3, 416, 416) or (1, 3, 320, 320) with multiplier of 32 as spatial shape
